# Generated by Django 6.0.7 on 2026-08-02 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_add_trending_score_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('upvote', 'Upvote'), ('comment', 'Comment'), ('share', 'Share')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'interaction_type'], name='feeds_inter_event_i_6f09a4_idx'), models.Index(fields=['user', 'created_at'], name='feeds_inter_user_id_41095d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'event', 'interaction_type'), name='unique_user_event_interaction')],
            },
        ),
    ]
