repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.14
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/biomejs/pre-commit
    rev: "v1.8.3"
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.8.3"]
