# Generated by Django 6.0.7 on 2026-07-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_alter_topic_description_alter_topic_name_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='curators', to='topics.topic'),
        ),
    ]
