# Generated by Django 6.0.7 on 2026-07-31 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatortopic',
            name='creator_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='users.creatorprofile'),
        ),
        migrations.AddField(
            model_name='creatortopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creators', to='topics.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='creatortopic',
            unique_together={('creator_profile', 'topic')},
        ),
    ]
