# Generated by Django 6.0.7 on 2026-07-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.DeleteModel(
            name='CreatorTopic',
        ),
    ]
