# Generated by Django 6.0.7 on 2026-07-31 09:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('topics', '0003_alter_topic_description_alter_topic_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={'ordering': ['display_order', 'created_at']},
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='narrative',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='narrative',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='events', to='topics.topic'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_set', to='events.event'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='media_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('image', 'Image'), ('document', 'Document')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='source_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'created_at'], name='events_even_status_72a590_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['event', 'display_order'], name='events_evid_event_i_d47d98_idx'),
        ),
    ]
