# Generated by Django 6.0.7 on 2026-08-02 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_evidence_options_event_updated_at_and_more'),
        ('topics', '0003_alter_topic_description_alter_topic_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_interaction_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='trending_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-trending_score'], name='events_even_trendin_ba659a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-last_interaction_at'], name='events_even_last_in_9193f8_idx'),
        ),
    ]
