# Generated by Django 6.0.7 on 2026-08-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_add_trending_score_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='r2_quarantine_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='upload_status',
            field=models.CharField(choices=[('url_based', 'URL Based'), ('pending_upload', 'Pending Upload'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='url_based', max_length=20),
        ),
    ]
